#!/bin/bash
FIRESIM_CONFIGS=/scratch/edwinlim/hyperscale-soc-chipyard/generators/mempress/software/firesim-configs-FASED
FIRESIM_DEPLOY=/scratch/edwinlim/hyperscale-soc-chipyard/sims/firesim/deploy

# Rocket sims
cp ${FIRESIM_CONFIGS}/FASED_megaboom_config_runtime_metasim.yaml ${FIRESIM_DEPLOY}/config_runtime.yaml
firesim infrasetup
firesim runworkload
