#!/bin/bash
set -ex

FIRESIM_CONFIGS=/scratch/edwinlim/hyperscale-soc-chipyard/generators/mempress/software/firesim-configs-FASED-dev
FIRESIM_DEPLOY=/scratch/edwinlim/hyperscale-soc-chipyard/sims/firesim/deploy

# Rocket sims
cp ${FIRESIM_CONFIGS}/FASED_64KBL2_4MBLLC_hyperscale_rocket_memstride.yaml ${FIRESIM_DEPLOY}/config_runtime.yaml
firesim infrasetup
firesim runworkload
